### ISSUE TITLE
make env_url optional

### ISSUE THREAD

**Issue by stevie-** [bobheadxi/deployments#11]
I don't need to set an `env_url` and deployment api doesn't require to have `environment_url` to be set.

In the example, `env_url` is also not set. https://github.com/bobheadxi/deployments/blob/master/README.md#L182-186

Please make `env_url` optional. https://github.com/bobheadxi/deployments/blob/master/src/main.ts#L66

Thanks.

**Comment by bobheadxi** [comment]
Good catch, thanks! It is now default in [`v0.4.1`](https://github.com/bobheadxi/deployments/releases/tag/v0.4.1)
