### ISSUE TITLE
Warning: The set-output command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by OlegoO** [bobheadxi/deployments#147]
Hi, we are using bobheadxi/deployments@master in our github actions.

During investigations into reason of Warning: The set-output command is deprecated and will be disabled soon. warning, we found that

Run bobheadxi/deployments@master
Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Do you have any plan to fix it?

**Comment by buckett** [comment]
Development is being done on the `main` branch and so if you want the latest fixes you should use `bobheadxi/deployments@main`. I think `master` is left around so it doesn't break existing builds.

If you want something more stable there's `bobheadxi/deployments@v1` and this should include a fix for the set-output warning.
