### ISSUE TITLE
Bump node version to 20

### ISSUE THREAD

**Issue by msdinit** [bobheadxi/deployments#162]
Hi!

Github [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) Node 16 actions and started to display warnings requesting to update.

Not sure if it's just a version bump in action.yml or if it requires some deeper changes

**Comment by mmckane** [comment]
would second this update request.

**Comment by asvishnyakov** [comment]
@bobheadxi Is there any chance you will close this issue?
