### ISSUE TITLE
Is there any way to overwrite the github-actions[bot] user?

### ISSUE THREAD

**Issue by gugaiz** [bobheadxi/deployments#19]
When I generate a deploy, they appear as they are deployed by `github-actions[bot]`. Is there any way to overwrite this with the actual user that is doing the deployment?

**Comment by bobheadxi** [comment]
Unfortunately, I don't think so - the only way to change this I believe is to use a custom auth token under the desired user instead of `secrets.GITHUB_TOKEN`

Each deployment is still attached to a GitHub commit however, which will have the author

**Comment by bobheadxi** [comment]
Closing for now - feel free to reopen if you have any additional questions!
