### ISSUE TITLE
README examples not up to date

### ISSUE THREAD

**Issue by y-nk** [bobheadxi/deployments#50]
1. At creation:
- when passing:

```
id: deployment
```

warning is thrown:

```
Warning: Unexpected input(s) 'id', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref', 'env', 'transient', 'deployment_id', 'env_url', 'status']
```

**Comment by bobheadxi** [comment]
Are you placing `id` under the `with` block? the top-level `id` field is an official step identifier and should not trigger this warning (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsid)

**Comment by y-nk** [comment]
since it was an urgent matter i moved away from this solution already. feel free to ask more questions for enquiry if you wish to solve this, or close the issue if you prefer not to mind (both are fine for me, i totally understand we're all busy people).
