### ISSUE TITLE
multiple url in finish

### ISSUE THREAD

**Issue by rap2hpoutre** [bobheadxi/deployments#51]
Is there a way (in case of a repository deploys various URLs, such as API, WWW, etc.) to specify multiple URLs in the finish step? The goal is to be able to test a whole environment that can consist of multiple URLs.

**Comment by bobheadxi** [comment]
Unfortunately not - the URL parameter is provided by the GitHub API, and accepts a single URL:

https://docs.github.com/en/rest/reference/repos#create-a-deployment-status

> Sets the URL for accessing your environment.

What you can do is provide a link to a debug endpoint on one service of your environment, and have that endpoint list URLs for the various components of your environment

**Comment by bobheadxi** [comment]
Feel free to let me know if you have any other questions!
