### ISSUE TITLE
Error: unexpected error encountered: API rate limit exceeded for installation ID 12770951.

### ISSUE THREAD

**Issue by gajus** [bobheadxi/deployments#67]
```
Run bobheadxi/deployments@v0.6.1
  with:
    deployment_id: 469535842
    env_url: https://***/
    status: success
    step: finish
    token: ***
    no_override: true
    log_args: false
targeting contra/contra-web-app
finishing deployment for 469535842 with status success
Error: unexpected error encountered: API rate limit exceeded for installation ID 12770951.
```

Not clear where this error is coming from or how to mitigate it.

**Comment by bobheadxi** [comment]
It appears you are hitting the rate limit for your GitHub credentials or application - what token is provided? Is it from a bot account that is used for a lot of automation on this repository?

**Comment by bobheadxi** [comment]
@gajus I'm pretty sure this can be fixed by creating a bot account, and using a token from a bot account to ensure that the bot will always have available API request quotas :) Please feel free to ping me if you have any more questions!

(also very cool to see Contra using this action! 😁 )
