### ISSUE TITLE
Add support for passing a payload through?

### ISSUE THREAD

**Issue by jessebye** [bobheadxi/deployments#86]
We use payloads to include some important data, such as an AWS account ID to deploy to. It'd be great if we could pass in a `payload` input and have that be passed through in the GitHub API requests.

**Comment by bobheadxi** [comment]
What specific fields do you have in mind that you want passed through to the GitHub API? I'm a bit hesitant to add an option to provide a complete payload

**Comment by jessebye** [comment]
We pass things like a kubernetes namespace, AWS account ID, and AWS region in the payload.

**Comment by bobheadxi** [comment]
Sorry if I wasn't clear, I meant what _GitHub API_ fields 😄 e.g. from the list in https://docs.github.com/en/rest/reference/deployments#create-a-deployment-status

**Comment by jessebye** [comment]
Ah :) In particular, we want to pass `payload` in the Create a Deployment request: https://docs.github.com/en/rest/reference/deployments#create-a-deployment

**Comment by bobheadxi** [comment]
Oh! My bad - I did not realize `payload` was a actual field, I thought you were referring to the entire request payload 😅 I can definitely add this

**Comment by bobheadxi** [comment]
This is now available of the `v1` tag: https://github.com/bobheadxi/deployments/tree/v1

**Comment by jessebye** [comment]
Amazing! Thanks @bobheadxi for being so responsive :)
